server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://altaria.proxy.rlwy.net:48459/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:bKrXRyrpUUTxmkXWeQWRYWaLyxCEmDba}
spring.datasource.driver-class-name=org.postgresql.Driver

security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:M3c5aDRlZzcyYTZiOGQ5ZTBmMWMyZDNlNGY1ZzZoN2k=}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
